### ISSUE TITLE
server build for linux

### ISSUE THREAD

**Issue by huglester** [martincyprus/wtc-miner-monitor#2]
Hello,

I think it would be good idea if compiled version would have linux version of server too.

// inside server/ I get this (while compiling under linux)
go get
4d63.com/tz
../../4d63.com/tz/tz.go:36:10: undefined: time.LoadLocationFromTZData

**Comment by martincyprus** [comment]
so much for go being OS agnostic hehe ok, I will have a look at this.. I know what the problem is, just have to figure out some sensible way code around it.. the 4d63 was added because windows does not have a proper timezone location database.. so included one, but could be that under linux its having a bit of a problem.. will check this on my linux machine tomorrow and fix accordingly.

I'll start adding compiled version for linux as well, at least of the server :)

**Comment by huglester** [comment]
Thank you in thisbissue too:)))

**Comment by martincyprus** [comment]
was not able to reproduce the problem in linux (ubuntu 18.04 64bit, go 1.10) 

but to make it easier I have attached a linux server executable to the 1.0 release, try that if trouble compiling.

**Comment by huglester** [comment]
thank you. I was trying on debian with 1.9go. maybe it was a case.
then I'll set up the VM and check if It works. Since I need to compile for raspberyrpi, arm7 :)

**Comment by huglester** [comment]
Well, go1.10 went me further.
when starting WTC on arm7, I get this message:
2018/06/13 09:34:33 http: panic serving 192.168.88.253:55176: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
goroutine 66 [running]:

so I tried compiling with CGO_ENABLED=1;

Linux compiled:
$ CGO_ENABLED=1 go build -o server-linux
( NO ERRORS)


$ CGO_ENABLED=1 GOARM=7 GOARCH=arm GOOS=linux go build -o server-arm7
runtime/cgo
gcc: error: unrecognized command line option '-marm'


Any ideas?

Thank you!

**Comment by huglester** [comment]
For those who will find this issue :) 
to build for ARM (on Ubuntu 16.04), you need go version 1.10:
sudo apt-get install gcc-arm-linux-gnueabihf
CC=/usr/bin/arm-linux-gnueabihf-gcc CGO_ENABLED=1 GOARM=7 GOARCH=arm GOOS=linux go build -o server-arm7
